### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by f8chicken** [D-Programming-Deimos/openssl#110]
i migrated from debian bullseye to debian bookworm

openssl version 3.0.11 
but it is 32 bit x86, yes the old machine i have
so i edit again the line alias SSLOptionType to int

no compile error on bullseye ( dont know the ssl version)

error on bookworm :
openssl/source/deimos/openssl/ssl.di(717,43): Error: function `deimos.openssl.ssl.SSL_CTX_ctrl(ssl_ctx_st* ctx, int cmd, int larg, void* parg)` is not callable using argument types `(ssl_ctx_st*, int, ulong, typeof(null))`

openssl/~master/openssl/source/deimos/openssl/ssl.di(717,43):        cannot pass argument `op` of type `ulong` to parameter `int larg`

symmetry_thrift_d/1.0.8/symmetry_thrift_d/src/thrift/transport/ssl.d(252,21): Error: template instance `deimos.openssl.ssl.SSL_CTX_set_mode!()` error instantiating

**Comment by CyberShadow** [comment]
I believe this was fixed in https://github.com/D-Programming-Deimos/openssl/pull/114.
