### ISSUE TITLE
Start using tagged versions

### ISSUE THREAD

**Issue by s-ludwig** [D-Programming-Deimos/openssl#17]
This is mostly about using Deimos bindings as DUB packages, but of course in theory it is also useful for direct GIT based usage.

Applying to the other bindings as well, It would be good to start creating version tags, using a scheme that converts the underlying original library versions to SemVer (not sure how exactly OpenSSL handles backwards compatibility for the second and third digits). The original library version could be prepended as "build metadata", which is ignored for comparing versions:

v1.0.0+openssl.1.0.0e
v1.0.1+openssl.1.0.0e
v1.0.2+openssl.1.0.0l
v1.1.0+openssl.1.0.1g (or v2.0.0+openssl.1.0.1g?)

It's of course not really critical now, because there haven't been any big changes in the bindings recently, but it would be good if people could depend on v1.0.*, being sure to stay in sync with a particular OpenSSL branch and not get breakage. On top of that, ["~master" style dependencies will be deprecated](http://forum.rejectedsoftware.com/groups/rejectedsoftware.dub/thread/1020/) in DUB over a maybe 2 year period, after which it becomes mandatory to use version based dependencies instead of depending on a branch (it will still be possible to use packages that don't define any version tags, though).

The only issue of course is that this cannot be maintained using pull requests, but requires someone with push access. But in principle, I'd be willing to help out here if necessary.

**Comment by jeking3** [comment]
I think the important thing is to make sure the version of this deimos is appropriately revised when openssl is revised; for example the last release was "v1.1.6+1.0.1g" and it was only compatible with OpenSSL 1.0.  Pull requests have been merged that make it only compatible with OpenSSL 1.1, so the next version should be something like "v1.2.0+1.1.0h", and folks can use either "~>v1.1.6" for OpenSSL 1.0 compatibily, or "~>v1.2.0" for OpenSSL 1.1 compatibility in their dependencies, correct?

**Comment by s-ludwig** [comment]
It has become `v2.0.0-1.1.0h` now, since OpenSSL 1.1.0 removes a few things from 1.0.x and thus requires a new SemVer major version. But I guess we can safely close this now, since the version scheme from above has already been established by now.
