### ISSUE TITLE
#16 broke compilation

### ISSUE THREAD

**Issue by Abscissa** [D-Programming-Deimos/openssl#20]
Pull #16's usage of `uint16_t` and `uint32_t` causes this to no longer compile for me (using Win32, haven't tried on other platforms, so I'm not sure if it's Win32-specific or not).

**Comment by jeking3** [comment]
Is this still an issue?

**Comment by Abscissa** [comment]
Unfortunately, I'm not sure whether it's still an issue. TBH, it's been long enough that I (unfortunately) have no recollection of what I was even working on that led to this problem :(.
