### ISSUE TITLE
DMD trunk 2.0.67* can not compile this

### ISSUE THREAD

**Issue by mingodad** [D-Programming-Deimos/openssl#26]
Test program:

---

import std.stdio;
import deimos.openssl.ossl_typ;

void main()
{
    writeln("Hello World!");
}

---

Result:

---

dmd test_d_2_0_67.d 
deimos/openssl/ossl_typ.d(209): Error: undefined identifier ssl_ctx_st
deimos/openssl/ssl.d(435): Error: ExternC!(extern (C) c_long function(SSL_CTX\* ctx, int cmd, c_long larg, void\* parg)) had previous errors
deimos/openssl/ssl.d(447): Error: ExternC!(extern (C) c_long function(SSL_CTX\* s, int cb_id, ExternC!(extern (C) void function()) fp)) had previous errors

**Comment by jeking3** [comment]
Is this still an issue?

**Comment by Cogitri** [comment]
I don't think so.

**Comment by Geod24** [comment]
@CyberShadow : We can close this
