### ISSUE TITLE
Please release an OpenSSL 1.1 version

### ISSUE THREAD

**Issue by jeking3** [D-Programming-Deimos/openssl#41]
The code to integrate with OpenSSL 1.1 has been checked in for a while (See #39 from June 10) but nobody has made a release.  Please make a release.  Recommend using the tag `v1.1.7+1.1.0h`

**Comment by schveiguy** [comment]
Hm... I would, but the release numbers seem weird. @s-ludwig can you explain how the release tags should work? Latest is `v1.1.6+1.0.1g` I don't know what that `+1.0.1g` means.

**Comment by wilzbach** [comment]
That the release was based on `1.0.1g` from openssl.
Though you could tag e.g. be `v1.2.0+1.1.0`

**Comment by jeking3** [comment]
The first part of the version number is the deimos module version number.
The second part of the version number is the OpenSSL version headers it was created against.
If you need to support OpenSSL 1.0 then you need to use the `v1.1.6+1.0.1g` release tag.
If you need to support OpenSSL 1.1 then you need to use master until another tag is created.
That's why I opened this issue.

**Comment by jeking3** [comment]
@wilzbach If we use `v1.1.7-1.1.0h` as a tag then if openssl ever goes to v1.2 we have a chance at aligning to it.

**Comment by schveiguy** [comment]
I just did it, hopefully correctly.

**Comment by s-ludwig** [comment]
This appears to have broken the OpenSSL 1.0.x build of vibe.d: `..\vibe\tls\vibe\stream\openssl.d(589,36): Error: undefined identifier SSLv23_client_method, did you mean function SSLv3_client_method?`

This needs to be `v2.0.0+1.1.0h` instead, if there are any intended breaking changes.

**Comment by schveiguy** [comment]
OK, so can we untag a release then?

**Comment by s-ludwig** [comment]
Should be okay in this case I guess. The registry should also pick that up.

**Comment by s-ludwig** [comment]
Thanks! The new version has been picked up already. But yeah, releases here are indeed quite fragile, especially since there is no real sanity check, such as project tester integration. I'll try to keep an eye on this, too, although it may be necessary to explicitly poke me when a new release is necessary (I can't really keep up with github notifications currently).

**Comment by schveiguy** [comment]
> (I can't really keep up with github notifications currently)

I have 14k unread GH notifications. I'm probably just going to delete them all.

**Comment by jeking3** [comment]
Ah I see, yes, I suppose this would be considered a major bump.  Sorry for the bad information on the tagging that drove that to happen.  `v2.0.0+1.1.0h` works.
