### ISSUE TITLE
Consider bumping the version to address mismatching bindings

### ISSUE THREAD

**Issue by AlexAltea** [D-Programming-Deimos/openssl#62]
Latest tag `v2.0.1+1.1.0h` claims to use OpenSSL `v1.1.0h`, however the structure definitions do not match such headers:

E.g. see how `x509_st::cert_info` differs in indirection: 
- https://github.com/D-Programming-Deimos/openssl/blob/v2.0.1%2B1.1.0h/deimos/openssl/x509.d#L286
- https://github.com/openssl/openssl/blob/OpenSSL_1_1_0h/crypto/include/internal/x509_int.h#L144

Helpers such as [`X509_get_notBefore`](https://github.com/D-Programming-Deimos/openssl/blob/v2.0.1+1.1.0h/deimos/openssl/x509.d#L617), will try to dereference `cert_info`, even if the structure was generated flat by `libcrypto`, thus corrupting memory.

This issue has been addressed at some point between `v2.0.1+1.1.0h` and `master` however no new version has been issued.
Could you please create a new tag?

**Comment by s-ludwig** [comment]
Tagged v2.0.2+1.1.0h (already available on code.dlang.org)

**Comment by AlexAltea** [comment]
Thank you, this solved the issue!
