### ISSUE TITLE
Support for OpenSSL 3.0

### ISSUE THREAD

**Issue by Geod24** [D-Programming-Deimos/openssl#65]
The OpenSSL team has released a new version on 2021-09-07.
It comes with many changes, including a switch to actual Semver.
Announcement here: https://www.openssl.org/blog/blog/2021/09/07/OpenSSL3.Final/

**Comment by zoujiaqing** [comment]
How wonderful! Thanks @Geod24  for providing OpenSSL 3.0.0 support! After all these years of supporting newer OpenSSL libraries, this is exactly the base ecology the community needs.

**Comment by Geod24** [comment]
I'll close this as we are more or less there.
