### ISSUE TITLE
pre-generate fails when using gdc

### ISSUE THREAD

**Issue by SingingBush** [D-Programming-Deimos/openssl#94]
When using gdc the [scripts/generate_version.d](https://github.com/D-Programming-Deimos/openssl/blob/6cfe2339c67fc0a12a21cbe11f55374e268c8a32/scripts/generate_version.d) script fails:

```
Running pre-generate commands for openssl...
gdc: error: unrecognized command-line option ‘-run’
Command failed with exit code 1: gdc -run scripts/generate_version.d
```

**Comment by CyberShadow** [comment]
We need to be invoking gdmd for `-run`. @Geod24 Any ideas?

**Comment by Geod24** [comment]
I think that's why we had dub in the script in the first place and that's proof we should have kept it.

**Comment by CyberShadow** [comment]
I think it would be OK to invoke Dub from Dub.

Dub could also expose a `$DMD` variable that would point to `gdmd`/`ldmd` appropriately.

**Comment by SingingBush** [comment]
I would suggest, as Geod, that using dub to run a d file may be better. After installing gdc on Fedora Linux I get `/usr/bin/gdc` but there is no `/usr/bin/gdmd`, is [gdmd](https://github.com/D-Programming-GDC/gdmd) part of the gdc releases? I'd expect not otherwise gdc would probably handle `-run`. Perhaps this is an issue for @ibuclaw to resolve on [gdc](https://github.com/D-Programming-GDC/gcc) but if that's not going to happen for one reason or another then the _preGenerateCommands_ is going to have to change. Either run the script using dub or put some logic in there to check if the value of `$DC` and do something else for gdc.

**Comment by CyberShadow** [comment]
> After installing gdc on Fedora Linux I get `/usr/bin/gdc` but there is no `/usr/bin/gdmd`, is [gdmd](https://github.com/D-Programming-GDC/gdmd) part of the gdc releases?

If GDC is packaged then probably so should gdmd be, either as part of the same package or another package. Please contact your distribution's packager regarding this.

> I think it would be OK to invoke Dub from Dub.

Oops, I missed that this is how it used to be but it was changed because it caused problems: https://github.com/D-Programming-Deimos/openssl/pull/90

**Comment by SingingBush** [comment]
just in case I tried `dnf install gdmd` and can confirm that gdmd is not available in Fedora repo at the minute. I've raised it on the redhat bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2132651

**Comment by SingingBush** [comment]
Does `generate_version.d` need to run with the same compiler as the actual program? If it's just producing a source file `version_.di` then surely the build script could be run with dmd regardless of which compiler is used to compile the project. So perhaps just replace `$DC` with `dmd` and let people know in readme that dmd is needed regardless of which compiler you are using

**Comment by CyberShadow** [comment]
Unfortunately DMD is available for fewer architectures as GDC/LDC, so that would e.g. break building on AArch64.

**Comment by CyberShadow** [comment]
Reviewing the Dub code I remembered that Dub treats `gdc` and `gdmd` as different compilers, so I suggest you try this:

1. Get `gdmd`
2. Try building with `--compiler=gdmd`

**Comment by CyberShadow** [comment]
I'm guessing the above comment resolves this issue.
